name: Ping

on:
  schedule:
    - cron: "*/5 * * * *"
    - cron: "2-59/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Health Endpoint
        run: |
          curl --max-time 60 -f https://finance.tushargoel.in/health
